### PR TITLE
Added Unstake button to StakeOverview page

### PR DESCRIPTION
**Pull request by eswarasai**
### Description
- [x] Added Unstake button on StakeOverview page

### Screen Capture
unstake-min

Fixes: #74 
Bounty: https://gitcoin.co/issue/cennznet/runanode/74/3426

### CODE REVIEW

**Comment by benxgao** [comment]
Thanks for your PR, please have a look at our PR practice, and we will start PR review once those actions are checked. 
https://github.com/cennznet/runanode/blob/master/docs/PULL_REQUEST_TEMPLATE.md

**Comment by eswarasai** [comment]
@benxgao - Updated the PR as per the template checks. Let me know in case I've missed something. Thanks!

**Comment by benxgao** [comment]
@eswarasai 

Thanks for your PR, please check if you are allowed to do the following actions:

- [ ] Added @benxgao @CaiYiLiang as reviewers;
- [ ] Labelled `PR is ready to review` when all the above items have all been ticked;

**Comment by eswarasai** [comment]
@benxgao - Nope. I don't think Contributors can assign reviewers nor labels to a PR. So not really sure why it's been put up in the template.

**Comment by bengao-cennznet** [comment]
Thanks @eswarasai , it may be caused by our repository setting, we will figure it out, and before that, we are going to update the pull request template based on your feedback.

As per solution you provided is okay, but I think it would be better to get the component of `header with stake/unstake button` be more reusable, because we may add more  staking pages with that styles and we do not need to repeat that code segments.

I have created a branch based on my understanding, would you mind taking a review and see if there was anything could be improved? 

Otherwise, would you mind creating a new PR based on that branch, and I appreciate testing GIFs could be attached based on that solution?

**Comment by benxgao** [comment]
Thanks @eswarasai , it may be caused by our repository setting, we will figure it out, and before that, we are going to update the pull request template based on your feedback.

As per solution you provided is okay, but I think it would be better to get the component of header with stake/unstake button be more reusable, because we may add more staking pages with that styles and we do not need to repeat that code segments.

I have created a branch based on my understanding, would you mind taking a review and see if there was anything could be improved?

Otherwise, would you mind creating a new PR based on that branch, and I appreciate testing GIFs could be attached based on that solution?

**Comment by eswarasai** [comment]
@benxgao - Sorry about the radio silence. I've just had a quick look of the changes on that branch. I'll spend some time testing it and shall create a PR using that as a base branch in case any modifications are needed. Thanks!

**Pull request closed without merging**
